wcs_tv_show_manager:
    resource: "@WCSTvShowManagerBundle/Resources/config/routing.yml"
    prefix:   /

subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

